### ISSUE TITLE
서울시 데이터 / 위치 데이터 딜레이

### ISSUE THREAD

**Issue by xoxojw** [kimhwanhoon/20230724_team_project#22]
사용자 위치 데이터를 먼저 받아오고 나서 -> 그 위치 데이터를 기반으로 서울시에서 받은 데이터를 사용자 위치와 가까운 순으로 정렬해서 렌더링하고 싶은데
현재는 서울시 데이터가 먼저 받아지고, 위치 데이터가 그 이후에 받아져서
InitialState인 남산타워 기준으로 데이터가 정렬되어 렌더링되었다가, 다시 사용자 위치 기준으로 데이터가 재렌더링되는 문제

버그는 아니지만 UX 측면에서 해결하고 싶어서 이슈 남깁니다..!

**Comment by kimhwanhoon** [comment]
방금 확인하고 업데이트 했습니다~!

로딩시간때문 맵을 못 보는 단점이 있지만 로딩 애니메이션을 추가했고, 덕분에 처음에 남산타워로 로딩되었다가 다른 곳으로 움직이는 버그는 없어졌습니다.

`Map.jsx`
```js
const [isItLoading, setIsItLoading] = useState(true);

useEffect(() => {
    // latitude === 37.551086 && longitude === 126.988033는 redux 모듈에서 설정한 initialState값
    if (latitude === 37.551086 && longitude === 126.988033) {
      setIsItLoading(true);
    } else {
      setIsItLoading(false);
    }
  }, [latitude, longitude]);

// 로딩 로직 추가
return (
    <>
      {isItLoading ? (
        <StyledLoadingDiv>
          <div id="loading"></div>
          <h1>Map is loading</h1>
        </StyledLoadingDiv>
      ) : (
        <StyledDiv>
          <MapDiv style={mapStyle}>
            <NaverMap
              defaultCenter={new navermaps.LatLng(latitude, longitude)}
              defaultZoom={9}
              minZoom={6}
              maxZoom={15}
              ref={setMap}
              disableKineticPan={false}
            >
              <MarkPins map={map} boundary={boundary} />
              <MyLocationIcon onClick={() => currentLocationIconClickHandler()} id="map-current-location" />
            </NaverMap>
          </MapDiv>
        </StyledDiv>
      )}
    </>
  );
```

`const StyledLoadingDiv = styled.div`
```css
const StyledLoadingDiv = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  gap: 1rem;
  width: 750px;
  height: 500px;
  border-radius: 15px;
  box-shadow: 1px 1px 10px 0 rgba(39, 39, 39, 0.6);

  #loading {
    border: 6px solid rgba(0, 0, 0, 0.3); /* 스피너 테두리 스타일 */
    border-top: 6px solid #284a58; /* 스피너 상단 테두리 스타일 (로딩 효과 색상) */
    border-radius: 50%; /* 원형 스피너 모양을 위해 반지름 설정 */
    width: 60px;
    height: 60px;
    animation: spin 2s linear infinite; /* @keyframes 이름, 시간, 타이밍 함수, 무한 반복 설정 */
  }
  /* @keyframes 정의로 로딩 스피너 애니메이션 설정 */
  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    } /* 360도 회전 */
  }
  h1 {
    font-size: 1.2rem;
  }
`;
```
